services:

  product-service:
    container_name: product-service
    build: product-service
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: products

networks:
  ecommerce: